name: CI
on:
   push:
      paths-ignore:
         - 'README.md'
         - '**.mdx'
         - '.storybook/**'
         - '.husky/**'
      branches:
         - 'master'
jobs:
   build:
      runs-on: ubuntu-latest
      if: "!contains(github.event.head_commit.message, '[skip ci]')"

      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Use Node 12
           uses: actions/setup-node@v1
           with:
              node-version: 12.x

         - name: Use cached node_modules
           uses: actions/cache@v2
           with:
              path: node_modules
              key: nodeModules-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                 nodeModules-

         - name: Install dependencies
           run: npm install

         - name: Lint
           run: npm run lint

         - name: Build
           run: npm run build

         - name: 'Automated Version Bump'
           uses: 'phips28/gh-action-bump-version@master'
           with:
              tag-prefix: ''
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
